### ISSUE TITLE
Cant get elasticsearch 2 to work with travis.

### ISSUE THREAD

**Issue by mckeankylej** [mckeankylej/es-test#1]
As you can see from build [#2](https://travis-ci.org/mckeankylej/es-test/builds/180242830#L298) I cant get elasticsearch version 2 to work. It says it cant find java but in build [#6](https://travis-ci.org/mckeankylej/es-test/builds/180246033) which uses elasticsearch 1 in finds java. If I try `apt-get install default-jre` it doesn't work either. I need your help on this as it is the only thing stopping travis building at layer3. I gave you commit access. 
cc @andrewthad

**Comment by andrewthad** [comment]
Thanks. I'll look into this.

**Comment by andrewthad** [comment]
Bam: https://travis-ci.org/mckeankylej/es-test/builds/180432442

**Comment by andrewthad** [comment]
Here's where I stole this from: https://gist.github.com/mkorkmaz/254cd7c46a6fbcf79804158b4a6fb013
